### PR TITLE
Add support for Scala 2.12.19 and 2.13.13

### PR DESCRIPTION
**Pull request by lefou**
Depends on
* [x] https://github.com/com-lihaoyi/acyclic/pull/114 - required build plugin
* [x] https://github.com/com-lihaoyi/acyclic/pull/117 - required build plugin
* [x] https://github.com/typelevel/kind-projector/pull/271 - required build plugin
* [x] https://github.com/com-lihaoyi/Ammonite/pull/1422 - required build plugin
* [x] https://github.com/com-lihaoyi/Ammonite/pull/1424 - required build plugin
* [x] https://github.com/typelevel/kind-projector/pull/272 - required build plugin
* [x] https://github.com/com-lihaoyi/Ammonite/pull/1436 - fix CI test suite

Fix https://github.com/com-lihaoyi/Ammonite/issues/1420

### CODE REVIEW

**Comment by tgodzik** [comment]
Maybe the server needs to be updated first?

**Comment by lefou** [comment]
@alexarchambault Any idea why the BSP server is failing for Scala 2.13.13, but not for 2.13.12? There is no obvious error message. Since you contributed the BSP server code, maybe you have an idea or can help out?

**Comment by lefou** [comment]
Looks like the BSP server tests fail for many more Scala versions, we just don't run these tests in CI. I saw them fail here: https://github.com/com-lihaoyi/Ammonite/pull/1436

It's probably OK to ignore them for now, since they already broken, but users haven't reported any issues about that. So releasing for latest Scala versions is IMHO better that holding back for some minor issues.

**Comment by lefou** [comment]
I handled the failing test in PR https://github.com/com-lihaoyi/Ammonite/pull/1436, since we see the same issues of older Scala versions.

**Pull request merged**
