### PR TITLE
Add support for Scala 2.13.14

### PR DESCRIPTION
**Pull request by panbingkun**
https://contributors.scala-lang.org/t/scala-2-13-14-release-planning/6581/12
image
`Scala 2.13.14` has been released, let's support it.

Depends on

- [x] https://github.com/com-lihaoyi/acyclic/pull/123
- [x] https://github.com/typelevel/kind-projector/pull/279

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @lefou 
This is the first time I submit pr to `/com-lihaoyi/Ammonite`. If there is anything wrong, please correct me.
My PR refers to the changes made by [Add support for Scala 2.12.19 and 2.13.13](https://github.com/com-lihaoyi/Ammonite/pull/1421)

**Comment by lefou** [comment]
Acyclic `0.3.12` release supports Scala `2.13.14`.

**Comment by panbingkun** [comment]
> Acyclic `0.3.12` release supports Scala `2.13.14`.

Okay, I have updated the version of `Acyclic` in the file `build.sc`.
Thank you very much for your timely help.

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun .

**Review by lefou — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
