### PR TITLE
Support Scala 2.13.11 and 2.12.18

### PR DESCRIPTION
**Pull request by lolgab**
- Update acyclic to 0.3.8

### CODE REVIEW

**Comment by LuciferYang** [comment]
master seems already support Scala 2.12.18 and Scala 2.13.11

**Comment by lolgab** [comment]
> master seems already support Scala 2.12.18 and Scala 2.13.11

This is targeting the 2.x branch which is used by Mill 0.10.x

**Review by lefou — APPROVED** [review]
Looks good to me. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Comment by lwronski** [comment]
Hi @lolgab, thank you for adding support for Scala `2.13.11` and `2.12.18`. Is it possible to create a new release of `amm` (`2.5.9`), which includes the bumped minor version of Scala?

**Comment by lefou** [comment]
I think @lolgab already tagged a release, but for some reasons the version was not picked up by CI. Probably because the tag was pushed after the CI jobs ran. Let me try to re-run them. In case it's urgent, you can use version `2.5.8-2-159ff8f6` already.

**Pull request merged**
