### PR TITLE
Update Scala to 2.12.18

### PR DESCRIPTION
**Pull request by LuciferYang**
This pr aims to make `Ammonite` to support Scala 2.12.18, and to achieve this goal, the following dependencies have been upgraded in this pr:

- Upgrade `com.lihaoyi:acyclic` from 0.3.6 to 0.3.7
- Upgrade `org.scalameta:semanticdb-scalac` and `"org.scalameta:trees` from 4.5.13 to 4.7.8

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is related to https://github.com/com-lihaoyi/Ammonite/issues/1349 .

**Comment by LuciferYang** [comment]
```
terminal[2.12.18].enablePluginScalacOptions 
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:acyclic_2.12.18:0.3.6 
	not found: /home/runner/.ivy2/local/com.lihaoyi/acyclic_2.12.18/0.3.6/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/com/lihaoyi/acyclic_2.12.18/0.3.6/acyclic_2.12.18-0.3.6.pom
	not found: https://scala-ci.typesafe.com/artifactory/scala-integration/com/lihaoyi/acyclic_2.12.18/0.3.6/acyclic_2.12.18-0.3.6.pom
```

 Seems there is additional dependency(com.lihaoyi:acyclic_2.12.18:0.3.6 ) need to be upgraded and released first?

**Comment by LuciferYang** [comment]
[04d2be6](https://github.com/com-lihaoyi/Ammonite/pull/1350/commits/04d2be600b18286f04ab2ab1da829e6d688d5e00) upgrade `com.lihaoyi:acyclic` to 0.37 to support Scala 2.12.18

**Comment by LuciferYang** [comment]
The test failed due to 

```
Failed to resolve ivy dependencies:Error downloading org.scalameta:semanticdb-scalac_2.12.18:4.5.13
  not found: /Users/yangjie01/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.18/4.5.13/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.18/4.5.13/semanticdb-scalac_2.12.18-4.5.13.pom
```

**Review by alexarchambault — APPROVED** [review]
Thanks @LuciferYang!

**Comment by LuciferYang** [comment]
Thanks @alexarchambault ~

**Comment by dongjoon-hyun** [comment]
Thank you so much everyone!

**Pull request merged**
