### PR TITLE
Update Scala to 3.1.0

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Status of this: it seems the compiler phase change (`FrontEnd` -> `TyperPhase`) messed things up… Nothing is compiled any more in `3.1.0`, and we get no output byte code at all. We might just be missing another phase.

https://github.com/lampepfl/dotty/commit/c4e530302662a393702751feb6f927d8ff03093b removed `FrontEnd` in dotty.

**Comment by alexarchambault** [comment]
Merging as we waited long enough for this. Will try `3.1.1` right after.

**Comment by alexarchambault** [comment]
Seems this created the same kind of issues as in https://github.com/com-lihaoyi/Ammonite/pull/1215 🤔

**Comment by alexarchambault** [comment]
https://github.com/com-lihaoyi/Ammonite/pull/1247 should fix that.

**Comment by timothyklim** [comment]
Hi @alexarchambault ! Release coming soon?

**Comment by alexarchambault** [comment]
@timothyklim Oh, I'm used to nightlies, like `2.5.1-6-5fce97fb`, which are published on Maven Central too. But yeah, let's cut a release.

**Pull request merged**
